version: "3.2"
volumes:
    opentpod-data-var:
    opentpod-db-data:
    opentpod-redis-data:
services:
    opentpod-db:
        image: postgres:12.0-alpine
        container_name: opentpod-db
        restart: always
        volumes:
            - opentpod-db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_DB: ${OPENTPOD_DB}
            POSTGRES_PASSWORD: ${OPENTPOD_DB_PASSWORD}
        ports:
            - 127.0.0.1:${OPENTPOD_DB_PORT}:5432
    opentpod-db-viewer:
        image: adminer
        container_name: opentpod-db-viewer
        restart: always
        depends_on:
            - opentpod-db
        ports:
            - 127.0.0.1:${OPENTPOD_DB_VIEWER_PORT}:20000
        depends_on:
            - opentpod-db
    opentpod-broker:
        image: rabbitmq
        container_name: opentpod-broker
        environment:
            - RABBITMQ_DEFAULT_USER=${OPENTPOD_RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${OPENTPOD_RABBITMQ_PASSWORD}
        ports:
            - 127.0.0.1:${OPENTPOD_BROKER_PORT}:5672
    opentpod-redis:
        container_name: opentpod-redis
        image: redis:4.0.5-alpine
        command: redis-server --appendonly yes
        volumes:
            - opentpod-redis-data:/data
        command:
            [
                "sh",
                "-c",
                'exec redis-server --requirepass "$OPENTPOD_REDIS_PASSWORD"',
            ]
        ports:
            - 127.0.0.1:${OPENTPOD_REDIS_PORT}:6379
