# Contains extra packages needed for development besides packages in environment.yml
name: opentpod-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=19.1.1
  - setuptools
  - psycopg2==2.8.3
  - autopep8
  - autoflake
  - isort
  - pudb
  - rope
  - nodejs
  - pip:
    - -r local.txt